### ISSUE TITLE
退款的条目请加上链接原消费条目的链接

### ISSUE THREAD

**Issue by jostyee** [amoshsueh/MOZE_3.0#11]
增加两者的关联性，否则只能依靠关键词检索。

**Comment by jostyee** [comment]
或者将买入的东西再次卖出，也有关联性。是否能参考DEVONthink的做法，给每个条目生成独立的item link，这样就能把交易都串起来。

**Comment by amoshsueh** [comment]
v3.0(53) 已支援退款功能
