### ISSUE TITLE
导出CSV的同时是不是也能将附件一并导出？

### ISSUE THREAD

**Issue by jostyee** [amoshsueh/MOZE_3.0#12]

**Comment by amoshsueh** [comment]
附件是指相關圖片包成一個壓縮檔嗎？

**Comment by jostyee** [comment]
嗯，另外CSV加一栏写入附件名称？

**Comment by amoshsueh** [comment]
目前 CSV 設計只是單純把記帳資料匯出成表單，讓用戶可以在電腦上查看，我覺得不太適合連相關圖片都一起導出，這應該會等到之後支援網頁版時，能夠直接讓用戶打開一個網頁看到你要的報表統計分析。

**Comment by jostyee** [comment]
Sure.
