### ISSUE TITLE
添加一个订阅制消费分析的功能

### ISSUE THREAD

**Issue by yx1100** [amoshsueh/MOZE_3.0#16]
能否在预算，或者报表分析这块，添加一个管理订阅制消费的功能。可以给支出添加一个专案、标签或者循环支出，符合的可以统一管理，方便看到每个月需要花费多少。毕竟现在订阅制也是个大趋势，越来越多。具体可以参考一个 App 叫 Bobby。

**Comment by amoshsueh** [comment]
管理訂閱制消費，你可以新增一個專案去歸納相關支出，本身紀錄就有支援重複性支出，我不太明白為什麼需要額外做一個卵裡訂閱消費制的功能。

或許你可以提供一些截圖說明一下，這樣我可能會比較好理解你的需求，謝謝！
