### ISSUE TITLE
2.x備份的預算項目至3.x錯誤

### ISSUE THREAD

**Issue by aa900031** [amoshsueh/MOZE_3.0#18]
> 在2.x裡有設定預算的項目若備份時都還沒使用到，在3.0載入資料庫後會被認為是「未設定預算」的項目！

原回報人：Facebook@Joseph Lin
版本：3.0(15)

**Comment by amoshsueh** [comment]
之後版本沒有收到類似問題，先 close 掉如果有發生在 reopen
