### ISSUE TITLE
全幣種信用卡記帳問題

### ISSUE THREAD

**Issue by amoshsueh** [amoshsueh/MOZE_3.0#2]
全幣種信用卡記帳問題，因為還款時是根據當天的匯率來算的，所以最後可以有一個統一修改某一記長週期的匯率的功能

**Comment by jostyee** [comment]
之前MoneyWiz的用法是标记为未完成，这样主dashboard有个单独界面会统一列出，在入账后手动修改数据。

**Comment by amoshsueh** [comment]
對帳頁面支援統一結算匯率功能
