### ISSUE TITLE
账号里的“记账天数”日期计算问题

### ISSUE THREAD

**Issue by jostyee** [amoshsueh/MOZE_3.0#20]
如果有填错的数据，比如A账号20150101有一条记录选错到B账号，即便后来修改回来到A，B账号的“记账天数”也会将20150101纳入进去，这样的话该项统计就没有意义了，我现在一个刚用一个月的账号显示644天就是这个原因。

**Comment by amoshsueh** [comment]
這是 2.0 版本的 issue，先 close
