### ISSUE TITLE
繳款提醒會重複計算到調整餘額的金額

### ISSUE THREAD

**Issue by pewsheen** [amoshsueh/MOZE_3.0#23]
紀錄如果是

* 一般支出 -1000
* 調整餘額 -5000

繳費提醒的金額會是 6000，但是信用卡裡面的剩餘帳款會是正確的 -5000

![photo_2019-02-15_11-44-55](https://user-images.githubusercontent.com/460329/52833335-3b469100-3117-11e9-93d3-7ba45e045515.jpg)

![photo_2019-02-15_11-44-58](https://user-images.githubusercontent.com/460329/52833321-31249280-3117-11e9-8712-507c26009396.jpg)

**Comment by amoshsueh** [comment]
謝謝回報問題，方便提供你的備份檔給我測試看看嗎？可以透過 email 備份寄至 mozeapp@gmail.com，謝謝！

**Comment by amoshsueh** [comment]
This issue should be fixed in latest version
