### ISSUE TITLE
使用标签筛选建立报表的问题

### ISSUE THREAD

**Issue by yx1100** [amoshsueh/MOZE_3.0#24]
使用报表功能，新增报表，当筛选条件使用的是「标签」时，

如果标签的筛选条件只有一个，例如只筛选「#AAA」，

当一条记录的标签不止一个时，例如一条支出的标签有「#AAA」「#BBB」，这条记录就不能在这个只筛选「#AAA」的报表中显示出来。这个报表只能显示只有「#AAA」这一个标签的记录。

**Comment by amoshsueh** [comment]
This issue should be fixed in latest version
